preprocessing:
  use_stemming: True
  remove_stop_words: False
  use_replacement_patterns: True
retrieval:
  number_ranked_documents: 10
  result_checking: False
  customized_ranking: False
  weight_popularity_score: 0.3
  perform_system_evaluation: False