preprocessing:
  use_stemming: True
  remove_stop_words: False
  use_replacement_patterns: True
retrieval:
  number_ranked_documents: 10
  result_checking: True
  customized_ranking: True
  weight_artist_popularity: 0.2
  weight_song_popularity: 0.1
  perform_system_evaluation: False
  customized_ranking_result_limit: 100